// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBT2FQVuoCYba45hpI2Cu9yy_wrARYPc4',
    appId: '1:235386524486:web:09f4d0dd47a24b2fa1cb47',
    messagingSenderId: '235386524486',
    projectId: 'janksters-logistics',
    authDomain: 'janksters-logistics.firebaseapp.com',
    storageBucket: 'janksters-logistics.firebasestorage.app',
    measurementId: 'G-3C5NGM8HCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_5jta_YWnDOKjx4COsT96JrkiY8Ck3Y8',
    appId: '1:235386524486:android:916b76ae5d1e6645a1cb47',
    messagingSenderId: '235386524486',
    projectId: 'janksters-logistics',
    storageBucket: 'janksters-logistics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ9mCxe6Abgt4Ihkf7poAtuMD7RJlF_s4',
    appId: '1:235386524486:ios:aa2d79979c75b08ea1cb47',
    messagingSenderId: '235386524486',
    projectId: 'janksters-logistics',
    storageBucket: 'janksters-logistics.firebasestorage.app',
    iosBundleId: 'com.example.jankstersLogisticsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ9mCxe6Abgt4Ihkf7poAtuMD7RJlF_s4',
    appId: '1:235386524486:ios:aa2d79979c75b08ea1cb47',
    messagingSenderId: '235386524486',
    projectId: 'janksters-logistics',
    storageBucket: 'janksters-logistics.firebasestorage.app',
    iosBundleId: 'com.example.jankstersLogisticsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBT2FQVuoCYba45hpI2Cu9yy_wrARYPc4',
    appId: '1:235386524486:web:70075a455b5a4eb0a1cb47',
    messagingSenderId: '235386524486',
    projectId: 'janksters-logistics',
    authDomain: 'janksters-logistics.firebaseapp.com',
    storageBucket: 'janksters-logistics.firebasestorage.app',
    measurementId: 'G-PZZ6PL4GQZ',
  );
}
